name: continue-on-error-hack
on:
  schedule:
    - cron: '0 * * * *'
      #
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        target: [A, B, C]
    
    steps:
      - name: Work
        run: |
          if [ ${{ matrix.target }} == "B" ]
          then
            exit 1
          fi

  check-result:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Check result
        run: |
          for status in $(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ github.token }}" \
            "https://github.com/api/v3/repos/sebastiaopamplona/continue-on-error-hack/actions/runs/${{ github.run_id }}/jobs" | jq -r ".jobs[] | .conclusion")
            do
              if [ ${status} == "failure" ]
              then
                exit 1
              fi
            done
